export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';

export const FETCH_COUNTRY_DETAIL_REQUEST = 'FETCH_COUNTRY_DETAIL_REQUEST';
export const FETCH_COUNTRY_DETAIL_SUCCESS = 'FETCH_COUNTRY_DETAIL_SUCCESS';
export const FETCH_COUNTRY_DETAIL_FAILURE = 'FETCH_COUNTRY_DETAIL_FAILURE';
